### ISSUE TITLE
Consider recommending TaskGroup

### ISSUE THREAD

**Issue by balupton** [yoshuawuyts/the-tiny-guide-to-non-fancy-node#1]
https://github.com/bevry/taskgroup - example: https://github.com/bevry/taskgroup/wiki/Introduction-&-Usage

Would go well with the error point, as tasks are wrapped in domains by default, so even async throws are caught and can be handled correctly by the task or taskgroup that contains it - as well as using the same API for both serial and parallel, with only concurrency config changing

**Comment by yoshuawuyts** [comment]
Heya, I tend to treat errors like crashes so I'm not sure this fits that narrative. Also I only feel comfortable recommending solutions that I've tried and tested. It'd be real cool to see other's take on this though, the more people share their set of packages and styles, the better it'd be for us all I reckon.

So I'm going to politely decline this addition, but I hope you feel inspired enough to create your own list and I'll be happy to link to it. Cheers! ✌️

**Comment by balupton** [comment]
@yoshuawuyts cool, that's a good point - currently got https://github.com/bevry/base - but expanding that into a complete overview of what we use and why would go a long way
