### ISSUE TITLE
Consider referencing maxogden/mississippi

### ISSUE THREAD

**Issue by michaelrhodes** [yoshuawuyts/the-tiny-guide-to-non-fancy-node#2]
Nice guide! I thought it might be worth expanding the streams paragraph to mention [maxogden/mississippi](https://github.com/maxogden/mississippi)—not as a module you should actually require, but as a great README to reference when working with streams.

**Comment by max-mapper** [comment]
my dog

**Comment by jamen** [comment]
In addition to this, might be worth mentioning [pull-stream](https://github.com/pull-stream/pull-stream)?  Goes with the stuff said about functions and error handling.

**Comment by yoshuawuyts** [comment]
@michaelrhodes thanks, linked to it!

@jamen I'm a big fan of pull-streams - event to the point where I'm part of the org, but I don't use them in my day to day work. I think despite their superior design, they're not quite as practical as sticking to Node streams.
